language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
env:
  - DB=sqlite
script: 
  - RAILS_ENV=production bundle exec rake db:migrate --trace
#before_script:
#  - mysql -e 'create database my_app_test'
#  - psql -c 'create database my_app_test' -U postgres
#bundler_args: --binstubs=./bundler_stubs
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
